### ISSUE TITLE
Looks like its not supporting adding sp for collections with multiple partitions

### ISSUE THREAD

**Issue by svdeepakk** [JohnLTaylor/CosmosDbRepository#16]

**Comment by svdeepakk** [comment]
try
                    {
                        await _client.CreateStoredProcedureAsync(resourceResponse.Resource.AltLink, sp);
                    }
                    catch (DocumentClientException dex) when (dex.StatusCode ==                                                                                            HttpStatusCode.Conflict)
                    {
                        var updatedSp  = sps.First(p => p.Id == sp.Id);
                        updatedSp.Body = sp.Body;
                        await _client.ReplaceStoredProcedureAsync(updatedSp);
                    }

**Comment by JohnLTaylor** [comment]
Has been added
